### ISSUE TITLE
Data exported from wit doesn't load

### ISSUE THREAD

**Issue by nabihach** [RasaHQ/rasa-nlu-trainer#21]
I'm using the online version of your tool. I tried uploading the `demo-flights.json` file (available in Rasa examples). It doesn't work. I even tried adding the common_examples tag (as in `demo-rasa.json`), but no luck. Any tips?

**Comment by azazdeaz** [comment]
Hi @nabihach!

That example json is in wit format so the editor won't find any examples in it. Here is a demo json that you can try with: https://github.com/RasaHQ/rasa_nlu/blob/master/data/examples/rasa/demo-rasa.json
