### ISSUE TITLE
'NoneType' object has no attribute '_formatter_parser' error

### ISSUE THREAD

**Issue by dhilipPalanisamy** [RasaHQ/rasa-nlu-trainer#29]
@tmbo 
I am using MITIE backend for rasa-nlu server.
When i execute localhost:5000/parse?q=I am looking for Chinese food', i am getting 'NoneType' object has no attribute '_formatter_parser' from string.py file.
Thanks in advance..

Here is my config file.
{
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/examples/rasa/demo-rasa.json"
}

Please let me know if any other details is needed.

**Comment by azazdeaz** [comment]
Hey, @dhilipPalanisamy!

This package is only for the example editor tool. You probably wanted to open an issue in the https://github.com/RasaHQ/rasa_nlu repo.
