### ISSUE TITLE
how to use rasa-nlu-trainer for creating chatbot

### ISSUE THREAD

**Issue by sunipa21** [RasaHQ/rasa-nlu-trainer#36]
Hi,

I could setup the RASA-NLU-Trainer and able to work on localhost but not getting the upload and download option. Please suggest is it expected?Also I am not sure the how to use it  for creating chatbot? 
It is not actually an issue but I was not getting any idea so expecting that I may get some guidance here. Please guide me on this.

Best Regards,
Sunil

**Comment by azazdeaz** [comment]
Hi @sunipa21,

When you run the trainer locally it will open and edit your training file on your disk.
https://github.com/RasaHQ/rasa-nlu-trainer#launch

(This tool is probably not up to date with the latest version of Rasa at the moment, please see [docs](https://core.rasa.ai/tutorial_basics.html))
