### ISSUE TITLE
'rasa-nlu-trainer' command not working on terminal

### ISSUE THREAD

**Issue by sameerkumar16** [RasaHQ/rasa-nlu-trainer#37]
It's showing following error  

>
usr/local/lib/node_modules/rasa-nlu-trainer/server.js:17
  pkg,
     ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

>

**Comment by azazdeaz** [comment]
Hi @sameerkumar16! Which nodejs version are you using?

**Comment by sameerkumar16** [comment]
v0.10.25

**Comment by sameerkumar16** [comment]
npm -1.3.10

**Comment by azazdeaz** [comment]
Please try to upgrade, it should work safely from v6 but v8 is the recent LTS version.

**Comment by Kanupriyagoyal** [comment]
(env) MacBook-Pro-5:chatbot $ npm i -g rasa-nlu-trainer
/Users/.npm-global/bin/rasa-nlu-trainer -> /Users/.npm-global/lib/node_modules/rasa-nlu-trainer/server.js
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.

+ rasa-nlu-trainer@0.2.7
updated 1 package in 4.09s

(env) MacBook-Pro-5:data $ rasa-nlu-trainer
-bash: rasa-nlu-trainer: command not found
(env) MacBook-Pro-5:data $ 

(env) MacBook-Pro-5:data $ npm --version
6.4.1
(env) MacBook-Pro-5:data $ node --version
v10.15.1

**Comment by im-singh** [comment]
I installed npm, node, rasa-nlu-trainer twice. But Now I solved that issue "command not found". My python command is not working. So I think you need to sure about  python and rasa-nlu installed. May be this help .Thank you

**Comment by naveensmart395** [comment]
same problem
