### ISSUE TITLE
Cannot modify Rasa-nlu-trainer code source

### ISSUE THREAD

**Issue by montacerdk** [RasaHQ/rasa-nlu-trainer#50]
Hello, 

I want to modify the Rasa-Nlu-trainer source code in order to modify the “Upload” and “Download” buttons instead of "Save" button, like so : 

![image](https://user-images.githubusercontent.com/26897940/44098031-038a110a-9fd7-11e8-8063-098fd6c64135.png)

To do that, I installed Rasa-nlu-trainer with the node command : `npm i -g rasa-nlu-trainer`.
This has created a project repo in this folder : C:\Users\{Username}\AppData\Roaming\nvm\v10.8.0\node_modules\rasa-nlu-trainer .
 
After modifying the source code of the project (isOnline.js, …), I builded the solution by running `npm run build` and then `npm start
`Finally, I lunched `localhost:4321`, nothing appears in the navigator.

Can someone help me to fix this problem please ?

Thank you.

**Comment by kinggreenhall** [comment]
Can you show me the code you modified?
