### ISSUE TITLE
Can't parse json file "testData.json" SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by Rosadojonathan** [RasaHQ/rasa-nlu-trainer#52]
Hey there!

I'm trying to launch rasa-nlu-trainer on my data by using the
`rasa-nlu-trainer -s ./testData.json` command but I get the following error 

![image](https://user-images.githubusercontent.com/25138966/47029055-e8f66300-d16a-11e8-90cd-1b5148f39770.png)

I'm using
`rasa-nlu-trainer@0.2.7` 
and the latest versions of npm and node.

**Comment by kishanmaxx** [comment]
Hey I am facing the same issue .....whats the solution

**Comment by archishj** [comment]
Same issue. Please share the solution

**Comment by tuxalket** [comment]
Hey,
any update on the issue?
https://rasahq.github.io/rasa-nlu-trainer/
you can use the online version i guess but have you found anything on this?
